name: Deploy to env

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: deploy eks
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - uses: azure/setup-kubectl@v3
      with:
         version: 'latest' # default is latest stable
         id: install

    - name: AWS Configs
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_SECRET }}
          
    - name: Update kube config
      run: aws eks update-kubeconfig --name eksclusterdemo --region ap-south-1

    - name: Deploy image to Amazon EKS
      run: |
        kubectl apply -f hello.yaml
